### ISSUE TITLE
Installer + Graphic system bugs

### ISSUE THREAD

**Issue by na-razie-bez-nicku** [SzymekkYT/RadianceOS#3]
I found some errors with the graphics system when changing the theme (screenshots) and with installer -
Formatting with the default disk size does not work

and a problem with the input system, when logging in you can even enter the escape key.
![obraz](https://github.com/SzymekkYT/RadianceOS/assets/87973435/dcea8ac8-7afb-4bed-9831-ad8970e848c6)

**Comment by SzymekkYT** [comment]
everything fixed!
